#SDDP files to read
[sddp_files]
file_name=["cmgdem.csv", "gerter.csv", "gerhid.csv"]

#SDDP cases paths
[sddp_cases]
paths=["C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF80",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF85",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF90",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF95",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF100",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF105",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF110",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF115",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF120",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF125",
       "C:\\Users\\brunoamaral\\Documents\\BrunoAmaral\\SDDP\\CasosPesquisaMercadoJulia\\PesquisaMercJulia_IF130"]

#Output directory
[pmc_model_output_dir]
output_path_dir=".\\Results"